/**
 * Pet Adoption System API
 * API for user registration, login, adopter preferences, shelter pet management, and recommendations in the Pet Adoption System.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@petadoption.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AdopterPreferencesPostRequest model module.
 * @module model/AdopterPreferencesPostRequest
 * @version 1.0.0
 */
class AdopterPreferencesPostRequest {
    /**
     * Constructs a new <code>AdopterPreferencesPostRequest</code>.
     * @alias module:model/AdopterPreferencesPostRequest
     */
    constructor() { 
        
        AdopterPreferencesPostRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AdopterPreferencesPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AdopterPreferencesPostRequest} obj Optional instance to populate.
     * @return {module:model/AdopterPreferencesPostRequest} The populated <code>AdopterPreferencesPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AdopterPreferencesPostRequest();

            if (data.hasOwnProperty('attributeId')) {
                obj['attributeId'] = ApiClient.convertToType(data['attributeId'], 'Number');
            }
            if (data.hasOwnProperty('weight')) {
                obj['weight'] = ApiClient.convertToType(data['weight'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AdopterPreferencesPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AdopterPreferencesPostRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} attributeId
 */
AdopterPreferencesPostRequest.prototype['attributeId'] = undefined;

/**
 * @member {Number} weight
 */
AdopterPreferencesPostRequest.prototype['weight'] = undefined;






export default AdopterPreferencesPostRequest;

