/**
 * Pet Adoption System API
 * API for user registration, login, adopter preferences, shelter pet management, and recommendations in the Pet Adoption System.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@petadoption.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AdoptionStatusGet200ResponseInner model module.
 * @module model/AdoptionStatusGet200ResponseInner
 * @version 4.0.0
 */
class AdoptionStatusGet200ResponseInner {
    /**
     * Constructs a new <code>AdoptionStatusGet200ResponseInner</code>.
     * @alias module:model/AdoptionStatusGet200ResponseInner
     */
    constructor() { 
        
        AdoptionStatusGet200ResponseInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AdoptionStatusGet200ResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AdoptionStatusGet200ResponseInner} obj Optional instance to populate.
     * @return {module:model/AdoptionStatusGet200ResponseInner} The populated <code>AdoptionStatusGet200ResponseInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AdoptionStatusGet200ResponseInner();

            if (data.hasOwnProperty('adoptionId')) {
                obj['adoptionId'] = ApiClient.convertToType(data['adoptionId'], 'Number');
            }
            if (data.hasOwnProperty('petId')) {
                obj['petId'] = ApiClient.convertToType(data['petId'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AdoptionStatusGet200ResponseInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AdoptionStatusGet200ResponseInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}



/**
 * @member {Number} adoptionId
 */
AdoptionStatusGet200ResponseInner.prototype['adoptionId'] = undefined;

/**
 * @member {Number} petId
 */
AdoptionStatusGet200ResponseInner.prototype['petId'] = undefined;

/**
 * @member {module:model/AdoptionStatusGet200ResponseInner.StatusEnum} status
 */
AdoptionStatusGet200ResponseInner.prototype['status'] = undefined;

/**
 * @member {Date} date
 */
AdoptionStatusGet200ResponseInner.prototype['date'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
AdoptionStatusGet200ResponseInner['StatusEnum'] = {

    /**
     * value: "Pending"
     * @const
     */
    "Pending": "Pending",

    /**
     * value: "Approved"
     * @const
     */
    "Approved": "Approved",

    /**
     * value: "Rejected"
     * @const
     */
    "Rejected": "Rejected"
};



export default AdoptionStatusGet200ResponseInner;

