/**
 * Pet Adoption System API
 * API for user registration, login, adopter preferences, shelter pet management, and recommendations in the Pet Adoption System.
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: support@petadoption.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AdoptionStatus from './AdoptionStatus';

/**
 * The AdoptionStatusGet200ResponseAllOfPayloadInner model module.
 * @module model/AdoptionStatusGet200ResponseAllOfPayloadInner
 * @version 5.0.0
 */
class AdoptionStatusGet200ResponseAllOfPayloadInner {
    /**
     * Constructs a new <code>AdoptionStatusGet200ResponseAllOfPayloadInner</code>.
     * @alias module:model/AdoptionStatusGet200ResponseAllOfPayloadInner
     */
    constructor() { 
        
        AdoptionStatusGet200ResponseAllOfPayloadInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AdoptionStatusGet200ResponseAllOfPayloadInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AdoptionStatusGet200ResponseAllOfPayloadInner} obj Optional instance to populate.
     * @return {module:model/AdoptionStatusGet200ResponseAllOfPayloadInner} The populated <code>AdoptionStatusGet200ResponseAllOfPayloadInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AdoptionStatusGet200ResponseAllOfPayloadInner();

            if (data.hasOwnProperty('adoptionId')) {
                obj['adoptionId'] = ApiClient.convertToType(data['adoptionId'], 'String');
            }
            if (data.hasOwnProperty('petId')) {
                obj['petId'] = ApiClient.convertToType(data['petId'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = AdoptionStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AdoptionStatusGet200ResponseAllOfPayloadInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AdoptionStatusGet200ResponseAllOfPayloadInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['adoptionId'] && !(typeof data['adoptionId'] === 'string' || data['adoptionId'] instanceof String)) {
            throw new Error("Expected the field `adoptionId` to be a primitive type in the JSON string but got " + data['adoptionId']);
        }
        // ensure the json data is a string
        if (data['petId'] && !(typeof data['petId'] === 'string' || data['petId'] instanceof String)) {
            throw new Error("Expected the field `petId` to be a primitive type in the JSON string but got " + data['petId']);
        }

        return true;
    }


}



/**
 * @member {String} adoptionId
 */
AdoptionStatusGet200ResponseAllOfPayloadInner.prototype['adoptionId'] = undefined;

/**
 * @member {String} petId
 */
AdoptionStatusGet200ResponseAllOfPayloadInner.prototype['petId'] = undefined;

/**
 * @member {module:model/AdoptionStatus} status
 */
AdoptionStatusGet200ResponseAllOfPayloadInner.prototype['status'] = undefined;

/**
 * @member {Date} date
 */
AdoptionStatusGet200ResponseAllOfPayloadInner.prototype['date'] = undefined;






export default AdoptionStatusGet200ResponseAllOfPayloadInner;

