/**
 * Pet Adoption System API
 * API for user registration, login, adopter preferences, shelter pet management, and recommendations in the Pet Adoption System.
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: support@petadoption.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class AdoptionStatus.
* @enum {}
* @readonly
*/
export default class AdoptionStatus {
    
        /**
         * value: "new"
         * @const
         */
        "new" = "new";

    
        /**
         * value: "pending"
         * @const
         */
        "pending" = "pending";

    
        /**
         * value: "approved"
         * @const
         */
        "approved" = "approved";

    
        /**
         * value: "rejected"
         * @const
         */
        "rejected" = "rejected";

    

    /**
    * Returns a <code>AdoptionStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/AdoptionStatus} The enum <code>AdoptionStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

