/**
 * Pet Adoption System API
 * API for user registration, login, adopter preferences, shelter pet management, and recommendations in the Pet Adoption System.
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: support@petadoption.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Pet model module.
 * @module model/Pet
 * @version 5.0.0
 */
class Pet {
    /**
     * Constructs a new <code>Pet</code>.
     * @alias module:model/Pet
     * @extends Object
     */
    constructor() { 
        
        Pet.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Pet</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Pet} obj Optional instance to populate.
     * @return {module:model/Pet} The populated <code>Pet</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Pet();

            ApiClient.constructFromObject(data, obj, 'String');
            

            if (data.hasOwnProperty('petId')) {
                obj['petId'] = ApiClient.convertToType(data['petId'], 'String');
            }
            if (data.hasOwnProperty('shelterUserId')) {
                obj['shelterUserId'] = ApiClient.convertToType(data['shelterUserId'], 'String');
            }
            if (data.hasOwnProperty('petName')) {
                obj['petName'] = ApiClient.convertToType(data['petName'], 'String');
            }
            if (data.hasOwnProperty('imageUrl')) {
                obj['imageUrl'] = ApiClient.convertToType(data['imageUrl'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Pet</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Pet</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['petId'] && !(typeof data['petId'] === 'string' || data['petId'] instanceof String)) {
            throw new Error("Expected the field `petId` to be a primitive type in the JSON string but got " + data['petId']);
        }
        // ensure the json data is a string
        if (data['shelterUserId'] && !(typeof data['shelterUserId'] === 'string' || data['shelterUserId'] instanceof String)) {
            throw new Error("Expected the field `shelterUserId` to be a primitive type in the JSON string but got " + data['shelterUserId']);
        }
        // ensure the json data is a string
        if (data['petName'] && !(typeof data['petName'] === 'string' || data['petName'] instanceof String)) {
            throw new Error("Expected the field `petName` to be a primitive type in the JSON string but got " + data['petName']);
        }
        // ensure the json data is a string
        if (data['imageUrl'] && !(typeof data['imageUrl'] === 'string' || data['imageUrl'] instanceof String)) {
            throw new Error("Expected the field `imageUrl` to be a primitive type in the JSON string but got " + data['imageUrl']);
        }

        return true;
    }


}



/**
 * @member {String} petId
 */
Pet.prototype['petId'] = undefined;

/**
 * @member {String} shelterUserId
 */
Pet.prototype['shelterUserId'] = undefined;

/**
 * @member {String} petName
 */
Pet.prototype['petName'] = undefined;

/**
 * @member {String} imageUrl
 */
Pet.prototype['imageUrl'] = undefined;






export default Pet;

