/**
 * Pet Adoption System API
 * API for user registration, login, adopter preferences, shelter pet management, and recommendations in the Pet Adoption System.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@petadoption.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PetUpdateInfoPutRequest model module.
 * @module model/PetUpdateInfoPutRequest
 * @version 1.0.0
 */
class PetUpdateInfoPutRequest {
    /**
     * Constructs a new <code>PetUpdateInfoPutRequest</code>.
     * @alias module:model/PetUpdateInfoPutRequest
     */
    constructor() { 
        
        PetUpdateInfoPutRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PetUpdateInfoPutRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PetUpdateInfoPutRequest} obj Optional instance to populate.
     * @return {module:model/PetUpdateInfoPutRequest} The populated <code>PetUpdateInfoPutRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PetUpdateInfoPutRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('comments')) {
                obj['comments'] = ApiClient.convertToType(data['comments'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PetUpdateInfoPutRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PetUpdateInfoPutRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['comments'] && !(typeof data['comments'] === 'string' || data['comments'] instanceof String)) {
            throw new Error("Expected the field `comments` to be a primitive type in the JSON string but got " + data['comments']);
        }

        return true;
    }


}



/**
 * @member {String} name
 */
PetUpdateInfoPutRequest.prototype['name'] = undefined;

/**
 * @member {String} comments
 */
PetUpdateInfoPutRequest.prototype['comments'] = undefined;






export default PetUpdateInfoPutRequest;

