/**
 * Pet Adoption System API
 * API for user registration, login, adopter preferences, shelter pet management, and recommendations in the Pet Adoption System.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@petadoption.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Recommendation model module.
 * @module model/Recommendation
 * @version 1.0.0
 */
class Recommendation {
    /**
     * Constructs a new <code>Recommendation</code>.
     * @alias module:model/Recommendation
     */
    constructor() { 
        
        Recommendation.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Recommendation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Recommendation} obj Optional instance to populate.
     * @return {module:model/Recommendation} The populated <code>Recommendation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Recommendation();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('pet_id')) {
                obj['pet_id'] = ApiClient.convertToType(data['pet_id'], 'Number');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Recommendation</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Recommendation</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} id
 */
Recommendation.prototype['id'] = undefined;

/**
 * @member {Number} pet_id
 */
Recommendation.prototype['pet_id'] = undefined;

/**
 * @member {Date} date
 */
Recommendation.prototype['date'] = undefined;

/**
 * @member {Number} status
 */
Recommendation.prototype['status'] = undefined;






export default Recommendation;

