/**
 * Pet Adoption System API
 * API for user registration, login, adopter preferences, shelter pet management, and recommendations in the Pet Adoption System.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@petadoption.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ShelterUpdateContactsPutRequest model module.
 * @module model/ShelterUpdateContactsPutRequest
 * @version 1.0.0
 */
class ShelterUpdateContactsPutRequest {
    /**
     * Constructs a new <code>ShelterUpdateContactsPutRequest</code>.
     * @alias module:model/ShelterUpdateContactsPutRequest
     */
    constructor() { 
        
        ShelterUpdateContactsPutRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ShelterUpdateContactsPutRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ShelterUpdateContactsPutRequest} obj Optional instance to populate.
     * @return {module:model/ShelterUpdateContactsPutRequest} The populated <code>ShelterUpdateContactsPutRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ShelterUpdateContactsPutRequest();

            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ShelterUpdateContactsPutRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ShelterUpdateContactsPutRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }
        // ensure the json data is a string
        if (data['address'] && !(typeof data['address'] === 'string' || data['address'] instanceof String)) {
            throw new Error("Expected the field `address` to be a primitive type in the JSON string but got " + data['address']);
        }

        return true;
    }


}



/**
 * @member {String} phone
 */
ShelterUpdateContactsPutRequest.prototype['phone'] = undefined;

/**
 * @member {String} address
 */
ShelterUpdateContactsPutRequest.prototype['address'] = undefined;






export default ShelterUpdateContactsPutRequest;

