/**
 * Pet Adoption System API
 * API for user registration, login, adopter preferences, shelter pet management, and recommendations in the Pet Adoption System.
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: support@petadoption.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Role from './Role';

/**
 * The UserGetProfileGet200ResponseAllOfPayload model module.
 * @module model/UserGetProfileGet200ResponseAllOfPayload
 * @version 5.0.0
 */
class UserGetProfileGet200ResponseAllOfPayload {
    /**
     * Constructs a new <code>UserGetProfileGet200ResponseAllOfPayload</code>.
     * @alias module:model/UserGetProfileGet200ResponseAllOfPayload
     */
    constructor() { 
        
        UserGetProfileGet200ResponseAllOfPayload.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserGetProfileGet200ResponseAllOfPayload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserGetProfileGet200ResponseAllOfPayload} obj Optional instance to populate.
     * @return {module:model/UserGetProfileGet200ResponseAllOfPayload} The populated <code>UserGetProfileGet200ResponseAllOfPayload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserGetProfileGet200ResponseAllOfPayload();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = Role.constructFromObject(data['role']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('imageUrl')) {
                obj['imageUrl'] = ApiClient.convertToType(data['imageUrl'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserGetProfileGet200ResponseAllOfPayload</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserGetProfileGet200ResponseAllOfPayload</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }
        // ensure the json data is a string
        if (data['address'] && !(typeof data['address'] === 'string' || data['address'] instanceof String)) {
            throw new Error("Expected the field `address` to be a primitive type in the JSON string but got " + data['address']);
        }
        // ensure the json data is a string
        if (data['imageUrl'] && !(typeof data['imageUrl'] === 'string' || data['imageUrl'] instanceof String)) {
            throw new Error("Expected the field `imageUrl` to be a primitive type in the JSON string but got " + data['imageUrl']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
UserGetProfileGet200ResponseAllOfPayload.prototype['id'] = undefined;

/**
 * @member {String} email
 */
UserGetProfileGet200ResponseAllOfPayload.prototype['email'] = undefined;

/**
 * @member {module:model/Role} role
 */
UserGetProfileGet200ResponseAllOfPayload.prototype['role'] = undefined;

/**
 * @member {String} name
 */
UserGetProfileGet200ResponseAllOfPayload.prototype['name'] = undefined;

/**
 * @member {String} phone
 */
UserGetProfileGet200ResponseAllOfPayload.prototype['phone'] = undefined;

/**
 * @member {String} address
 */
UserGetProfileGet200ResponseAllOfPayload.prototype['address'] = undefined;

/**
 * @member {String} imageUrl
 */
UserGetProfileGet200ResponseAllOfPayload.prototype['imageUrl'] = undefined;






export default UserGetProfileGet200ResponseAllOfPayload;

