/**
 * Pet Adoption System API
 * API for user registration, login, adopter preferences, shelter pet management, and recommendations in the Pet Adoption System.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@petadoption.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AdoptionStatusGet200ResponseInner from './model/AdoptionStatusGet200ResponseInner';
import AdoptionStoryGet200ResponseInner from './model/AdoptionStoryGet200ResponseInner';
import FailureApiResponse from './model/FailureApiResponse';
import PetAddProfilePostRequest from './model/PetAddProfilePostRequest';
import PetUpdateProfilePutRequest from './model/PetUpdateProfilePutRequest';
import Recommendation from './model/Recommendation';
import Role from './model/Role';
import SuccessApiResponse from './model/SuccessApiResponse';
import User from './model/User';
import UserGetProfileGet200Response from './model/UserGetProfileGet200Response';
import UserLoginPost200Response from './model/UserLoginPost200Response';
import UserLoginPostRequest from './model/UserLoginPostRequest';
import UserRegisterPostRequest from './model/UserRegisterPostRequest';
import UserUpdateProfilePutRequest from './model/UserUpdateProfilePutRequest';
import AdoptionApi from './api/AdoptionApi';
import MatchingApi from './api/MatchingApi';
import PetApi from './api/PetApi';
import UserApi from './api/UserApi';


/**
* API for user registration, login, adopter preferences, shelter pet management, and recommendations in the Pet Adoption System..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var PetAdoptionSystemApi = require('index'); // See note below*.
* var xxxSvc = new PetAdoptionSystemApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new PetAdoptionSystemApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new PetAdoptionSystemApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new PetAdoptionSystemApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 4.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AdoptionStatusGet200ResponseInner model constructor.
     * @property {module:model/AdoptionStatusGet200ResponseInner}
     */
    AdoptionStatusGet200ResponseInner,

    /**
     * The AdoptionStoryGet200ResponseInner model constructor.
     * @property {module:model/AdoptionStoryGet200ResponseInner}
     */
    AdoptionStoryGet200ResponseInner,

    /**
     * The FailureApiResponse model constructor.
     * @property {module:model/FailureApiResponse}
     */
    FailureApiResponse,

    /**
     * The PetAddProfilePostRequest model constructor.
     * @property {module:model/PetAddProfilePostRequest}
     */
    PetAddProfilePostRequest,

    /**
     * The PetUpdateProfilePutRequest model constructor.
     * @property {module:model/PetUpdateProfilePutRequest}
     */
    PetUpdateProfilePutRequest,

    /**
     * The Recommendation model constructor.
     * @property {module:model/Recommendation}
     */
    Recommendation,

    /**
     * The Role model constructor.
     * @property {module:model/Role}
     */
    Role,

    /**
     * The SuccessApiResponse model constructor.
     * @property {module:model/SuccessApiResponse}
     */
    SuccessApiResponse,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The UserGetProfileGet200Response model constructor.
     * @property {module:model/UserGetProfileGet200Response}
     */
    UserGetProfileGet200Response,

    /**
     * The UserLoginPost200Response model constructor.
     * @property {module:model/UserLoginPost200Response}
     */
    UserLoginPost200Response,

    /**
     * The UserLoginPostRequest model constructor.
     * @property {module:model/UserLoginPostRequest}
     */
    UserLoginPostRequest,

    /**
     * The UserRegisterPostRequest model constructor.
     * @property {module:model/UserRegisterPostRequest}
     */
    UserRegisterPostRequest,

    /**
     * The UserUpdateProfilePutRequest model constructor.
     * @property {module:model/UserUpdateProfilePutRequest}
     */
    UserUpdateProfilePutRequest,

    /**
    * The AdoptionApi service constructor.
    * @property {module:api/AdoptionApi}
    */
    AdoptionApi,

    /**
    * The MatchingApi service constructor.
    * @property {module:api/MatchingApi}
    */
    MatchingApi,

    /**
    * The PetApi service constructor.
    * @property {module:api/PetApi}
    */
    PetApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi
};
