/**
 * Pet Adoption System API
 * API for user registration, login, adopter preferences, shelter pet management, and recommendations in the Pet Adoption System.
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: support@petadoption.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Adoption from './model/Adoption';
import AdoptionStatus from './model/AdoptionStatus';
import AdoptionStatusGet200Response from './model/AdoptionStatusGet200Response';
import AdoptionStoryGet200Response from './model/AdoptionStoryGet200Response';
import AdoptionStoryGet200ResponseAllOfPayloadInner from './model/AdoptionStoryGet200ResponseAllOfPayloadInner';
import ApiResponse from './model/ApiResponse';
import MatchingRecommendationIdAcceptPut201Response from './model/MatchingRecommendationIdAcceptPut201Response';
import MatchingRecommendationNextGet200Response from './model/MatchingRecommendationNextGet200Response';
import MatchingRecommendationsGet200Response from './model/MatchingRecommendationsGet200Response';
import Pet from './model/Pet';
import PetGetProfileGet200Response from './model/PetGetProfileGet200Response';
import PetGetProfilePetIdGet200Response from './model/PetGetProfilePetIdGet200Response';
import Recommendation from './model/Recommendation';
import RecommendationStatus from './model/RecommendationStatus';
import Role from './model/Role';
import User from './model/User';
import UserGetProfileGet200Response from './model/UserGetProfileGet200Response';
import UserLoginPost200Response from './model/UserLoginPost200Response';
import UserLoginPost200ResponseAllOfPayload from './model/UserLoginPost200ResponseAllOfPayload';
import UserLoginPostRequest from './model/UserLoginPostRequest';
import UserRegisterPostRequest from './model/UserRegisterPostRequest';
import UserUploadImagePost200Response from './model/UserUploadImagePost200Response';
import AdoptionApi from './api/AdoptionApi';
import MatchingApi from './api/MatchingApi';
import PetApi from './api/PetApi';
import UserApi from './api/UserApi';


/**
* API for user registration, login, adopter preferences, shelter pet management, and recommendations in the Pet Adoption System..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var PetAdoptionSystemApi = require('index'); // See note below*.
* var xxxSvc = new PetAdoptionSystemApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new PetAdoptionSystemApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new PetAdoptionSystemApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new PetAdoptionSystemApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 5.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Adoption model constructor.
     * @property {module:model/Adoption}
     */
    Adoption,

    /**
     * The AdoptionStatus model constructor.
     * @property {module:model/AdoptionStatus}
     */
    AdoptionStatus,

    /**
     * The AdoptionStatusGet200Response model constructor.
     * @property {module:model/AdoptionStatusGet200Response}
     */
    AdoptionStatusGet200Response,

    /**
     * The AdoptionStoryGet200Response model constructor.
     * @property {module:model/AdoptionStoryGet200Response}
     */
    AdoptionStoryGet200Response,

    /**
     * The AdoptionStoryGet200ResponseAllOfPayloadInner model constructor.
     * @property {module:model/AdoptionStoryGet200ResponseAllOfPayloadInner}
     */
    AdoptionStoryGet200ResponseAllOfPayloadInner,

    /**
     * The ApiResponse model constructor.
     * @property {module:model/ApiResponse}
     */
    ApiResponse,

    /**
     * The MatchingRecommendationIdAcceptPut201Response model constructor.
     * @property {module:model/MatchingRecommendationIdAcceptPut201Response}
     */
    MatchingRecommendationIdAcceptPut201Response,

    /**
     * The MatchingRecommendationNextGet200Response model constructor.
     * @property {module:model/MatchingRecommendationNextGet200Response}
     */
    MatchingRecommendationNextGet200Response,

    /**
     * The MatchingRecommendationsGet200Response model constructor.
     * @property {module:model/MatchingRecommendationsGet200Response}
     */
    MatchingRecommendationsGet200Response,

    /**
     * The Pet model constructor.
     * @property {module:model/Pet}
     */
    Pet,

    /**
     * The PetGetProfileGet200Response model constructor.
     * @property {module:model/PetGetProfileGet200Response}
     */
    PetGetProfileGet200Response,

    /**
     * The PetGetProfilePetIdGet200Response model constructor.
     * @property {module:model/PetGetProfilePetIdGet200Response}
     */
    PetGetProfilePetIdGet200Response,

    /**
     * The Recommendation model constructor.
     * @property {module:model/Recommendation}
     */
    Recommendation,

    /**
     * The RecommendationStatus model constructor.
     * @property {module:model/RecommendationStatus}
     */
    RecommendationStatus,

    /**
     * The Role model constructor.
     * @property {module:model/Role}
     */
    Role,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The UserGetProfileGet200Response model constructor.
     * @property {module:model/UserGetProfileGet200Response}
     */
    UserGetProfileGet200Response,

    /**
     * The UserLoginPost200Response model constructor.
     * @property {module:model/UserLoginPost200Response}
     */
    UserLoginPost200Response,

    /**
     * The UserLoginPost200ResponseAllOfPayload model constructor.
     * @property {module:model/UserLoginPost200ResponseAllOfPayload}
     */
    UserLoginPost200ResponseAllOfPayload,

    /**
     * The UserLoginPostRequest model constructor.
     * @property {module:model/UserLoginPostRequest}
     */
    UserLoginPostRequest,

    /**
     * The UserRegisterPostRequest model constructor.
     * @property {module:model/UserRegisterPostRequest}
     */
    UserRegisterPostRequest,

    /**
     * The UserUploadImagePost200Response model constructor.
     * @property {module:model/UserUploadImagePost200Response}
     */
    UserUploadImagePost200Response,

    /**
    * The AdoptionApi service constructor.
    * @property {module:api/AdoptionApi}
    */
    AdoptionApi,

    /**
    * The MatchingApi service constructor.
    * @property {module:api/MatchingApi}
    */
    MatchingApi,

    /**
    * The PetApi service constructor.
    * @property {module:api/PetApi}
    */
    PetApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi
};
